services:
  - type: web
    name: portfolio-website
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn portfolio_site.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PANEL_PASSWORD
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0